module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "main-color": "#fb599a",
        "gray-lighter": "#E6E6E6",
        "gray-light": "#CFCFCF",
        "gray-base": "#A6A6A6",
        "gray-dark": "#6A6A6A",
        "gray-darker": "#3C3C3C",
        "gray-darkest": "#0B0105",
        "pink-lightest": "#FFE8F1",
        "pink-lighter": "#FDBED7",
        "pink-light": "#FD92BD",
        "pink-base": "#FB599A",
        "pink-darkest": "#DF216C",
        "red-lightest": "#ffe5e5",
        "red-lighter": "#ff9898",
        "red-light": "#ff6d6d",
        "red-base": "#ff5247",
        "red-darkest": "#d3180c",
        "green-lightest": "#ecfce5",
        "green-lighter": "#7dde86",
        "green-light": "#4cd471",
        "green-base": "#23c16b",
        "green-darkest": "#198155",
      },
    },
  },
  plugins: [],
};
